spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    rest:
      base-path: /data-api

taco:
  orders:
    pageSize: 10

logging:
  file:
    path: /var/logs/
    name: /var/logs/taco-cloud.log
  level:
    root: INFO
    org.springframework.security: INFO
