spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: <facebook client id>
            clientSecret: <facebook client secret>
            scope: email, public_profile
logging:
  file:
    path: /var/logs/
    name: /var/logs/taco-cloud.log
  level:
   root: INFO
   org.springframework.security: INFO