spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: <facebook client id>
            clientSecret: <facebook client secret>
            scope: email, public_profile
  data:
    rest:
      base-path: /data-api

taco:
  orders:
    pageSize: 10

logging:
  file:
    path: /var/logs/
    name: /var/logs/taco-cloud.log
  level:
    root: INFO
    org.springframework.security: INFO
